#!/bin/sh

readonly RESPONSE_FILE=/root/db2response.rsp

get_param() {
  local PARAM=`grep "^$1" $RESPONSE_FILE | cut -d* -f1 | cut -d= -f2 | sed -e 's/ //g'`
  if [ $PARAM ]; then
    echo $PARAM
  else
    echo $2
  fi
}

DB2_FILEPATH=`get_param FILE`

DB2_INST_NAME=`get_param DB2_INST.NAME db2inst1`
DB2_INST_UID=`get_param DB2_INST.UID 1001`
DB2_INST_GROUP_NAME=`get_param DB2_INST.GROUP_NAME db2iadm1`
DB2_INST_GID=`get_param DB2_INST.GID 901`
DB2_INST_PASSWORD=`get_param DB2_INST.PASSWORD db2inst1`
DB2_INST_HOME_DIRECTORY=`get_param DB2_INST.HOME_DIRECTORY /opt/db2inst1`

DB2_INST_FENCED_USERNAME=`get_param DB2_INST.FENCED_USERNAME db2sdfe1`
DB2_INST_FENCED_UID=`get_param DB2_INST.FENCED_UID 1002`
DB2_INST_FENCED_GROUP_NAME=`get_param DB2_INST.FENCED_GROUP_NAME db2fsdm1`
DB2_INST_FENCED_GID=`get_param DB2_INST.FENCED_GID 902`
DB2_INST_FENCED_PASSWORD=`get_param DB2_INST.FENCED_PASSWORD db2sdfe1`
DB2_INST_FENCED_HOME_DIRECTORY=`get_param DB2_INST.FENCED_HOME_DIRECTORY /opt/db2sdfe1`

DB2_INST_SVCENAME=`get_param DB2_INST.SVCENAME db2c_db2inst1`
DB2_INST_PORT_NUMBER=`get_param DB2_INST.PORT_NUMBER 50000`

DATABASE=`get_param DATABASE`
DATABASE_NAME=`get_param $DATABASE.DATABASE_NAME`
DATABASE_USERNAME=`get_param $DATABASE.USERNAME`
DATABASE_PASSWORD=`get_param $DATABASE.PASSWORD`


echo "DB2_INST.NAME=$DB2_INST_NAME"
echo "DB2_INST.UID=$DB2_INST_UID"
echo "DB2_INST.GROUP_NAME=$DB2_INST_GROUP_NAME"
echo "DB2_INST.GID=$DB2_INST_GID"
echo "DB2_INST.PASSWORD=$DB2_INST_PASSWORD"
echo "DB2_INST.HOME_DIRECTORY=$DB2_INST_HOME_DIRECTORY"

echo "DB2_INST.FENCED_USERNAME=$DB2_INST_FENCED_USERNAME"
echo "DB2_INST.FENCED_UID=$DB2_INST_FENCED_UID"
echo "DB2_INST.FENCED_GROUP_NAME=$DB2_INST_FENCED_GROUP_NAME"
echo "DB2_INST.FENCED_GID=$DB2_INST_FENCED_GID"
echo "DB2_INST.FENCED_PASSWORD=$DB2_INST_FENCED_PASSWORD"
echo "DB2_INST.FENCED_HOME_DIRECTORY=$DB2_INST_FENCED_HOME_DIRECTORY"

echo "DB2_INST.SVCENAME=$DB2_INST_SVCENAME"
echo "DB2_INST.PORT_NUMBER=$DB2_INST_PORT_NUMBER"

echo "DATABASE=$DATABASE"
echo "$DATABASE.DATABASE_NAME=$DATABASE_NAME"
echo "$DATABASE.USERNAME=$DATABASE_USERNAME"
echo "$DATABASE.PASSWORD=$DATABASE_PASSWORD"

if [ -e $DB2_FILEPATH ]
then

groupadd -g $DB2_INST_GID $DB2_INST_GROUP_NAME
groupadd -g $DB2_INST_FENCED_GID $DB2_INST_FENCED_GROUP_NAME
useradd -u $DB2_INST_UID -g $DB2_INST_GROUP_NAME -M -d $DB2_INST_HOME_DIRECTORY $DB2_INST_NAME
useradd -u $DB2_INST_FENCED_UID -g $DB2_INST_FENCED_GROUP_NAME -M -d $DB2_INST_FENCED_HOME_DIRECTORY $DB2_INST_FENCED_USERNAME
echo $DB2_INST_PASSWORD | passwd --stdin $DB2_INST_NAME
echo $DB2_INST_FENCED_PASSWORD | passwd --stdin $DB2_INST_FENCED_USERNAME

useradd $DATABASE_USERNAME
echo $DATABASE_PASSWORD | passwd --stdin $DATABASE_USERNAME

echo "$DB2_INST_SVCENAME   $DB2_INST_PORT_NUMBER/tcp" >> /etc/services

sudo -u db2inst1 -i db2start

else

/usr/local/src/expc/db2setup -r $RESPONSE_FILE
useradd $DATABASE_USERNAME
echo $DATABASE_PASSWORD | passwd --stdin $DATABASE_USERNAME

fi

